#Turma
### Cria uma nova turma
POST http://localhost:3003/turma/create
Content-Type: application/json

{     
    "name": "HHHHOOKS <3"   
}

### Mostra todas as turmas
GET http://localhost:3003/turmas

### Mostra todas as turmas ativas
GET http://localhost:3003/turmas/ativas

### Busca turmas por id
GET http://localhost:3003/turmas/1665010242337

### Edita modulo da turma
PUT http://localhost:3003/turma/modulo/edit/1665010242337?modulo=1

//////////////////////////////////////////////////////////////////////////////

# Estudante
### Cria um novo estudante
POST http://localhost:3003/estudante/create
Content-Type: application/json

{     
    "name": "Wictor",
    "email": "wictor@gmail.com" ,
    "data_nasc": "1993-08-13",
    "turma_id": "1665104632209" 
}

### Busca todos os estudantes
GET http://localhost:3003/estudantes

### Busca estudante pelo nome
GET http://localhost:3003/estudante/nome/?name=Wictor

### Altera estudante de turma
PUT http://localhost:3003/estudante/turma/edit
Content-Type: application/json

{     
    "id": "Wictor",
    "alteracao": "2" ,
    "coluna": "turma"
}

### Busca os hoobys dos estudantes
 GET http://localhost:3003/estudante/hobbys/1665104665605

//////////////////////////////////////////////////////////////////////////////