###
POST http://localhost:3003/turma/create
Content-Type: application/json

{     
    "name": "Hooks <3"   
}

### Traz todas as turmas
GET http://localhost:3003/turmas

### Traz as turmas ativas
GET http://localhost:3003/turmas/ativas

###
GET http://localhost:3003/turmas/1665010242337

###
PUT http://localhost:3003/turma/modulo/edit/1665010242337?modulo=1

###
POST http://localhost:3003/hobby/create
Content-Type: application/json

{
    "name":"Ler Livros"
}

###
GET http://localhost:3003/hobbys

###


###
POST http://localhost:3003/estudante/create
Content-Type: application/json

{
    "name" : "jessy",
    "email": "jessyY@gmail.com",
    "data_nasc": "1991/08/04",
    "turma_id":"1665073730104",
    "hobbies":["Ver instagram", "Dormir"]
}

###
GET http://localhost:3003/estudante/hobbys/1665078115772

###


